# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    font: 25pt \"Segoe UI\";\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#stackedWidget QPushButton {\n"
"    border: 2px solid rgb(203, 204, 200);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(203, 204, 200);\n"
"}\n"
"#stackedWidget QPushButton:hover {\n"
"    background-color: rgb(203, 204, 200);\n"
"    border: 2px solid rgb(152, 153, 150);\n"
"}\n"
"#stackedWidget QPushButton:pressed {    \n"
"    background-color: rgb(152, 153, 150);\n"
"    border: 2px solid rgb(152, 153, 150);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("border-image: url(:/images/images/background.jpg) 0 0 0 0 stretch stretch;")
        self.home_page.setObjectName("home_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_frame = QtWidgets.QFrame(self.home_page)
        self.title_frame.setStyleSheet("border-image: none;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.title_frame)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.title_frame)
        self.button_frame = QtWidgets.QFrame(self.home_page)
        self.button_frame.setStyleSheet("border-image: none;")
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.button_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_training = QtWidgets.QPushButton(self.button_frame)
        self.btn_training.setMinimumSize(QtCore.QSize(500, 60))
        self.btn_training.setMaximumSize(QtCore.QSize(500, 60))
        self.btn_training.setStyleSheet("")
        self.btn_training.setObjectName("btn_training")
        self.verticalLayout_4.addWidget(self.btn_training, 0, QtCore.Qt.AlignHCenter)
        self.btn_start_game = QtWidgets.QPushButton(self.button_frame)
        self.btn_start_game.setMinimumSize(QtCore.QSize(500, 60))
        self.btn_start_game.setMaximumSize(QtCore.QSize(500, 60))
        self.btn_start_game.setObjectName("btn_start_game")
        self.verticalLayout_4.addWidget(self.btn_start_game, 0, QtCore.Qt.AlignHCenter)
        self.btn_settings = QtWidgets.QPushButton(self.button_frame)
        self.btn_settings.setMinimumSize(QtCore.QSize(500, 60))
        self.btn_settings.setMaximumSize(QtCore.QSize(500, 60))
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout_4.addWidget(self.btn_settings, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.button_frame)
        self.stackedWidget.addWidget(self.home_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.stackedWidget.addWidget(self.settings_page)
        self.game_page = QtWidgets.QWidget()
        self.game_page.setObjectName("game_page")
        self.stackedWidget.addWidget(self.game_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; font-weight:600;\">BCI Hoops</span></p></body></html>"))
        self.btn_training.setText(_translate("MainWindow", "Training"))
        self.btn_start_game.setText(_translate("MainWindow", "Start Game"))
        self.btn_settings.setText(_translate("MainWindow", "Settings"))
from . resources_rc import *
